Repository Algo-Phantoms/Algo-Tree, pull requests merged in 2021-03, with the labels that each got.

#62 Added Linked List code in python
  Code/Python/linked_list.py
  Linked_list/readme.md
Labels: gssoc21

#209 Kahns Algorithm for issue #200 added
  Algorithm/Special_algo/readme.md
  Code/C++/Kahns_algorithm.cpp
Labels: Level0, gssoc21

#583 Tim sort in C++
  Algorithm/Searching_Sorting/readme.md
  Code/C++/tim_sort.cpp
Labels: Level2, gssoc21

#896 N Queen Problem Code (C++)
  Algorithm/Backtracking/readme.md
  Code/C++/n_queen_problem.cpp
Labels: Level1, gssoc21

#1166 Issue 535
  Code/C++/negative_cycle_in_weighted_graph.cpp
  Graph/readme.md
Labels: reviewing

#829 Reversing a linked list c++
  Code/C++/reverse_a_linked_list.cpp
  Linked_list/readme.md
Labels: reviewing
