Repository Algo-Phantoms/Algo-Tree, pull requests merged in 2021-04, with the labels that each got.

#539 [feature-1] staircase_search.cpp
  2D_Array/readme.md
  Algorithm/Searching_Sorting/readme.md
  Code/C++/staircase_search.cpp
Labels: Level1, gssoc21

#1417 Sudoku solver
  Algorithm/Backtracking/readme.md
  Code/Java/Sudoku_Solver.java
Labels: Level1, gssoc21

#1288 Added shortest common Supersequence in cpp
  Algorithm/DP/readme.md
  Code/C++/print_shortest_supersequence.cpp
Labels: Level1, gssoc21

#675 Add Level Order Traversal For Binary Tree (C++)
  Code/C++/level_order_traversal_binary_tree.cpp
Labels: reviewing

#208 Added Brian Kernighan Algorithm
  Algorithm/Bit_manipulation/readme.md
  Code/C++/Brian_Kernighan.cpp
Labels: Level1, gssoc21

#746 Added the code for Linear Search (Python)
  Algorithm/Searching_Sorting/readme.md
  Code/Python/linearsearch.py
Labels: reviewing

#1378 Added Climbing Stairs DP Solution
  Algorithm/DP/readme.md
  Code/C++/Climbing_Stairs.cpp
Labels: Level1, gssoc21

#1401 CircularQueue in Java
  Code/Java/CircularQueue
  Queue/readme.md
Labels: Level1, gssoc21

#1458 Reverse a string in CPP
  Code/C++/reverse_string.cpp
  string/readme.md
Labels: Level0, gssoc21

#1244 Brian Kernighan's Algorithm
  Algorithm/Bit_manipulation/readme.md
  Code/Java/BrianKernighanAlgorithm.java
Labels: Level1, gssoc21

#1394 Generate all valid parentheses - Java
  Algorithm/Recursion/readme.md
  Code/Java/valid_parantheses.java
Labels: Level1, gssoc21

#1186 Root to leaf path with given sum
  Code/C++/Root_to_leaf_path_with_given_sum.cpp
  Tree/readme.md
Labels: Level1, gssoc21

#591 Added rat_in_maze.cpp
  Algorithm/Backtracking/readme.md
  Code/C++/rat_in_maze.cpp
Labels: reviewing

#1478 Reverse a string in Java
  Code/Java/reverse_string.java
  string/readme.md
Labels: Level0, gssoc21

#1050 Implemented Floyd-Warshall Algorithm
  Code/C++/Floyd_Warshall.cpp
  Graph/readme.md
Labels: reviewing

#628 Jump_Game in Java
  Algorithm/Greedy/readme.md
  Code/Java/Jump_Game.java
Labels: Level0, gssoc21

#359 Bucket Sort using C++
  Algorithm/Searching_Sorting/readme.md
  Code/C++/bucket_sort.cpp
Labels: Level0, gssoc21

#1641 Book Allocation in Java
  Algorithm/Searching_Sorting/readme.md
  Code/Java/Book_Allocation.java
Labels: Level1, gssoc21

#946 Repeating and missing Number Java
  Array/readme.md
  Code/Java/Repeating_And_Missing_Number.java
Labels: Level0, gssoc21

#1486 Inverse of an array
  Array/readme.md
  Code/C++/inverse_of_an_array.cpp
Labels: Level0, gssoc21

#1370 Tower of Hanoi in Java
  Algorithm/Recursion/readme.md
  Code/Java/Tower_of_Hanoi.java
Labels: Level1, gssoc21

#133 2D Matrix Rotation
  2D_Array/readme.md
  Code/C++/2d_matrix_rotation_90degree_clockwise.cpp
Labels: Level0, gssoc21

#256 added display, change operations
  Code/C++/stack_class.cpp
Labels: reviewing

#1663 Added Topological sort and Dijkstra algorithm in Java language
  Code/Java/Dijkstra.java
  Code/Java/Topological_sort.java
  Graph/readme.md
Labels: Level1, gssoc21

#1631 Added program for implementation of queue in python
  Code/Python/queue.py
  Queue/readme.md
Labels: Level0, gssoc21

#1699 BFS Traversal of Binary Tree (in C++) and updated README
  Code/C++/binary_tree_BFS_traversal.cpp
  Tree/readme.md
Labels: Level0, cpp, gssoc21, tree

#1667 Added Unique Permutations of string c++
  Code/C++/readme.md
  Code/C++/unique_permutaions_of_string.cpp
Labels: Level0, cpp, gssoc21

#1703 Update README.md
  README.md
Labels: documentation

#1700 DFS Traversal of Binary Tree (in C++) and updated README
  Code/C++/binary_tree_DFS_traversal.cpp
  Tree/readme.md
Labels: Binary Tree, Level0, cpp, gssoc21

#1706 Brian Kernighan's Algorithm in python
  Algorithm/Bit_manipulation/readme.md
  Code/Python/Brian_Kernighan's_Algorithm.py
Labels: Level1, gssoc21, python

#1500 Find peak element using binary search in python
  Algorithm/Searching_Sorting/readme.md
  Code/Python/peak_element.py
Labels: Level0, gssoc21, python

#1436 Add circular queue (Basic Operations like Insert, Delete, Display elements etc)
  Code/Python/circular_queue.py
  Queue/readme.md
Labels: Level1, gssoc21, python

#1635 Added Trapping Rainwater problem in python
  Algorithm/Special_algo/readme.md
  Code/Python/trapping_rainwater.py
Labels: Level1, gssoc21, python

#1431 Tower of Hanoi in Python
  Code/Python/Tower_of_Hanoi.py
  Code/Python/readme.md
Labels: Level1, gssoc21

#1648 Kamenetsky formula
  Algorithm/Number_theory/readme.md
  Code/Java/Kamenetsky_Formula.java
Labels: Level0, Number Theory, gssoc21, java

#1691 Union of two array
  Array/readme.md
  Code/C++/Union_of_two_unsorted_array.cpp
Labels: Level0, array, cpp, gssoc21

#1745 Check Trimorphic Number -->Fixes[#1736]
  Algorithm/Number_theory/readme.md
  Code/C++/Trimorphic_number.cpp
Labels: Level0, Number Theory, cpp, gssoc21

#1661 code added
  Algorithm/Number_theory/readme.md
  Code/C++/palindrome_number.cpp
Labels: Level0, Number Theory, cpp, gssoc21

#1757 Added the code for K largest elements in increasing order #1752
  Array/readme.md
  Code/C++/K_largest_element.cpp
Labels: Heap, Level0, cpp, gssoc21

#1623 Manachers algo Added #758
  Code/Java/longPalindrome.java
  string/readme.md
Labels: Level1, gssoc21, java, string

#1622 Min no of Coins Added in Java #965 Done in JAVA
  Algorithm/Greedy/readme.md
  Code/Java/greedyalgo.java
Labels: Level0, greedy, gssoc21, java

#1599 Multiplication of Matrix Added in JAVA #727
  2D_Array/readme.md
  Code/Java/matrixop_mul.java.java
Labels: 2D array, Level1, gssoc21, java

#1771 Searching in BST ->Closes : [#1682]
  Searching in BST.Java
  Tree/readme.md
Labels: Level1, gssoc21, java

#1786 Added Maximum sum path from any node to any node in Binary Tree
  Code/C++/max_tree_path.cpp
  Tree/readme.md
Labels: Level2, cpp, gssoc21

#719 Peak Value in Array issue solved
  Array/readme.md
  Code/Java/peakvalueinarray.java
Labels: Level0, gssoc21

#1411 Taylor Series added in JAVA
  Algorithm/Number_theory/readme.md
  Code/Java/Taylorseries.java
Labels: Level2, gssoc21

#1802 Added maximum Topology Short
  Code/C++/Max_Topology_short.cpp
  Tree/readme.md
Labels: Level3, cpp, gssoc21

#1747 Trimorphic Number in Python #1736
  Algorithm/Number_theory/readme.md
  Code/Python/TrimorphicNumber.py
Labels: Level0, gssoc21, python

#1763 Toeplitz
  2D_Array/readme.md
  Code/Java/Toeplitz.java
Labels: 2D array, Level0, gssoc21

#1797 To find all unique prime factors of N
  Algorithm/Number_theory/readme.md
  Code/C++/Uique_prime_factor.cpp
Labels: Level0, Number Theory, gssoc21
